language: java
sudo: false
install: true
script:
  - git clone https://github.com/amine177/piJEE
  - cd piJEE/piJEE/piJEE-ejb
  - mvn clean install
  - mvn install:install-file -Dfile=target/piJEE-ejb-1.0.jar
  - cd ../../../piJavaFx
  - mvn clean install -nsu
