language: java
sudo: false
install: true
script:
  - git clone https://github.com/amine177/piJEE
  - cd piJEE/piJEE/
  - mvn clean install
  - mvn package
  #- cp target/piJEE-ejb-1.0.jar target/piJEE-ejb.jar
  #- mvn install:install-file -Dfile=target/piJEE-ejb.jar -DgroupId=tn.esprit.overpowered -Dpackaging=jar -DartifactId=piJEE-ejb -Dversion=1.0
  - cd ../../../piJavaFx
  - mvn clean install
